config/routes.rb
ModelCustmoers::Application.routes.draw do
  resources :customers do
    collection do
       post :import 
       get :inactive
       post :inactive       
     end
     member do
       get :deactive
       get :activate
      end
    resources :addresses
    resources :notes
    resources :contacts
  end
  resources :users do
    collection do
      get :forgot_password  
      post :forgot_password
      get :edit_password
      put  :edit_password
      get :inactive
      post :inactive
    end 
     member do
       get :deactive
       get :activate
      end
  end
    resources :addresses
    
    resources :contacts do
      resources :addresses
    end

    resources :notes

   resources :sessions
   root :to => 'sessions#new'
   match 'logout' => 'sessions#destroy', :as => :logout
  
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  attr_accessible :email, :password, :username,:password_confirmation, :role, :photo, :status
  
  validates_presence_of :username
  validates_presence_of :email 
  validates_uniqueness_of :username, :email , :on => :create
  validates_format_of :email,
                      :with => /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i , 
                      :message => 'invalid email'
  validates_presence_of :password,:on => :create
  validates_presence_of :password_confirmation,:on => :create
  validates_presence_of :role
  
  has_attached_file :photo, :styles => { :small => "150x150", :large => "300x300" ,:mini => "50x50"}

  do_not_validate_attachment_file_type :photo
 def self.search(search)  
    if search  
      where("username LIKE ?", "%#{search}%")  
    else  
      scoped  
    end  
  end  

  def activate
     self.status = 1
     self.save
  end

  def deactive
     self.status = 0
     self.save!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  layout "application"
  #before_filter :require_login, :except => [:forgot_password]
  before_filter :find_user, :except => [:index, :new, :create, :inactive, :forgot_password, :edit_password]

  def index
   @users = User.where(:status => 1)
   @users = @users.search(params[:search]).order("username").page(params[:page]).per(3)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      UserMailer.registration_confirmation(@user).deliver  
      redirect_to users_path, :notice => "Created New User!"
    else
      flash[:notice] = 'please enter valid details'
      render "new"
    end
  end

  def show
  end
  
  def edit
  end

  
  def update
      @user.update_attributes(params[:user])
      if @user.save
        UserMailer.change_password_confirmation(@user).deliver  
        redirect_to users_path(@user), :notice => "Updated"
      else
      render "edit"
    end
  end

  def edit_password
   if request.get?
   else
    if params[:password] != "" and params[:password_confirmation] != ""
        current_user.password = params[:password]
        current_user.password_confirmation = params[:password_confirmation]
        if  current_user.password == current_user.password_confirmation
          if current_user.save
           flash[:notice] = 'Your password has been changed'
            redirect_to customers_path
          end
        else
          flash[:notice] = 'Your password and password confirmation must match'
        end
     
    else
      flash[:notice] = 'Your password and password confirmation must match'
    end
      
   end


      
end
    
  def forgot_password
     if request.get?      
      else
       @user = User.find_by_email(params[:email])
       @user.password = rand(99999)
       if @user.save
        UserMailer.forgot_password_confirmation(@user).deliver  
        redirect_to root_url, :notice => "Your password is Send to Registered email id"
      else
        flash[:notice] = 'Invalid email-id'
        render "forgot_password"
     end
    end
  end
  

  def destroy
    @user.destroy
    redirect_to users_path
  end

def activate
    @user.activate
    redirect_to inactive_users_path
  end
  

  def deactive
    @user.deactive
    redirect_to users_path
  end


def inactive
   @users = User.where(:status => 0)
   @users = @users.search(params[:search]).order("username").page(params[:page]).per(3)
end

private
  def find_user
    @user = User.find(params[:id])
    if not @user
      raise  ActiveRecord::RecordNotFound
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for @user, :validate => true, :html => { :class => 'form-horizontal user_form' } do |f| %>

  <div class="control-group">
    <%= f.label :username, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :username, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
      
    </div>
  </div>
   <div class="control-group">
    
    <%= f.label :password_confirmation ,:class=>'control-label'%>
    <div class="controls">
    <%= f.password_field :password_confirmation, :class => 'text_field' %>
    
  </div>
</div>
 <div class="control-group">
    <%= f.label :role ,:class=>'control-label'%>
    <div class="controls">
    <%= f.select :role, options_for_select(["Admin", "User"]) %>
   </div>
</div>
 <p>
  <b> Picture </b><br/>
  <%= f.file_field :photo %>
 </p>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
    users_path, :class => 'btn' %>
  </div>
<% end %>


<%= stylesheet_link_tag "jquery-ui" %>
<%= javascript_include_tag  "jquery-1.9.1.js", 'jquery-ui', 'jquery.validate.js', 'jquery.validate.min.js' %>
<script>
  
function  validate_function(){
  
$(".user_form").validate({
  rules: {
    "user[username]": {
      required: true,
      minlength: 4
    },
    "user[email]": {
      required: true,
      email: true
    },
    "user[password]": {
      required: true,
      minlength:6
    },
    "user[password_confirmation]": {
      required: true,
      equalTo: "#user_password"
    }
  },
  messages: {
   "user[username]" : {
      required: "Name should not be blank",
      minlength: jQuery.format("At least {0} characters required!")
    },
   "user[email]" : {
      required: "We need your email address to contact you",
      email: "Your email address must be in the format of name@domain.com"
    },
   "user[password]" : {
      required: "password should not be blank",
      minlength: jQuery.format("At least {6} characters required!")
    },
   "user[password_confirmation]" : {
      required: "password should not be blank",
      equalTo: "password should not match"
    }
  }
});

}

$(document).ready(function() {
  validate_function();
  
$( "#datepicker" ).datepicker();

 });
</script>

app/views/users/edit.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/edit_password.html.erb
<h1>Reset Password</h1>

  <%= form_tag edit_password_users_path , :method => :put do %>
  <div class="field">
    <%= label_tag :New_password %>
    <%= password_field_tag :password %>
  </div>
  <div class="field">
    <%= label_tag :password_confirmation %>
    <%= password_field_tag :password_confirmation %>
  </div>
  	<%= submit_tag "Update" %>
<% end %>

app/views/users/forgot_password.html.erb
<div class = "login">
<%= form_tag :action=>'forgot_password' do %>
  <table align="center" cellspacing="2" cellpadding="3" border=0 class="login_table">
     <tr>
      <td colspan="2" align="center"><h1 class="head">Reset Password</h1></td></tr>
      <tr><th><%= label_tag :email %></th><td><%= text_field_tag :email, params[:email] %></td></tr>
      <tr><th></th><td colspan="2" align="left"><%= submit_tag "Send email" %></td></tr>
  </table>
 <% end %>
</div>

app/views/users/inactive.html.erb
<div class="page-header">
  <h1>Users</h1>
</div>

<table class="tablesorter" style="width:75%;border:1px solid; align:center;" align="center">

  <thead>
    <div class="abc">
    <tr style="height:50px">
      <th>Username</th>
      <th>Email</th>
      <th>Role</th>
      <th>Status</th>
    </tr>
    </div>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    <% if user.status == 0  %>
    <% if user.role=="User" %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to "Activate", activate_user_path(user), :class => 'btn' %>
      </tr>
      <% end %>
    <% end %>
    <% end %>
  </tbody>
  
  <br>
  
</div>
</table>
<div style="float:right; padding-right:28px;">
<%= paginate @users %>
 </div>
 <%= stylesheet_link_tag 'tablesorter.css' %>
<%= javascript_include_tag  'jquery.tablesorter.min' %>
<script type="text/javascript">

$(document).ready(function() { 
    $("#customer_table").tablesorter({   });  
  } 
</script>

app/views/users/index.html.erb
<div class="page-header">
  <h1>Users</h1>
</div>
<div align ="right" style = "width:85%;">
  <%= link_to "Add User", new_user_path, :class => 'btn'%>
</div>
<%= form_tag users_path, :method => 'get' do %>  
      <p> 
        <div style="float:left; padding-left:95px;" >

       <%= text_field_tag :search, params[:search] %>  
        <%= submit_tag "Search", :name => nil %> 
        </div>
      </p>  
    <% end %>  
<table class="tablesorter" id="user_table" style="width:85%;border:1px solid; align:center;" align="center">
  <thead>
    <tr style="height:50px ">
      <th>Username</th>
      <th>Email</th>
      <th>Role</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
    
    <% if user.role=="User" %>
    <% if user.status == 1  %>
      <tr>
        <td><%= link_to user.username, user_path(user.id) %></td>
        <td><%= user.email %></td>
        <td><%= user.role %></td>
        <td><%= link_to "Deactivate", deactive_user_path(user.id), :class => 'btn' %>
      </tr>
      <% end %>
    <% end %>
    <% end %>
  </tbody>
  
  <br>
  
</div>
</table>
<div style="float:right; padding-right:28px;">
<%= paginate @users %>
 </div>

<%= stylesheet_link_tag 'tablesorter.css' %>
<%= javascript_include_tag  'jquery.tablesorter.min' %>
<script type="text/javascript">

$(document).ready(function() { 
    $("#user_table").tablesorter({   });  
  } 
</script>

app/views/users/new.html.erb
<%- model_class = User -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/users/show.html.erb
<div class="page-header">
  <h1>User</h1>
</div>
<%= image_tag @user.photo(:small) %>
 <table width="100%">
          <tbody>
            <tr valign="top">
              <td align="left" style="width:190px;text-align:left;">
                <table  style="width:50%;">
                <tr>
                <th>Name</th>
                <td> <%= @user.username %></td></tr>
                <tr><th>Email</th><td><%= @user.email %></td></tr>
              </table>
        </table> 
<div class="form-actions">
 
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_user_path(@user), :class => 'btn', :rel => "facebox" %>
 
</div>
<%= stylesheet_link_tag "jquery-ui" %>
<%= stylesheet_link_tag "facebox" %>
<%= javascript_include_tag  "jquery-1.9.1.js", 'jquery-ui', 'jquery.validate.js', 'jquery.validate.min.js' %>
<%= javascript_include_tag "facebox.js" %>
<script>  
 jQuery(document).ready(function() {  
  $('a[rel*=facebox]').facebox();
 });
</script>