config/routes.rb
ModelCustmoers::Application.routes.draw do
  resources :customers do
    collection do
       post :import 
       get :inactive
       post :inactive       
     end
     member do
       get :deactive
       get :activate
      end
    resources :addresses
    resources :notes
    resources :contacts
  end
  resources :users do
    collection do
      get :forgot_password  
      post :forgot_password
      get :edit_password
      put  :edit_password
      get :inactive
      post :inactive
    end 
     member do
       get :deactive
       get :activate
      end
  end
    resources :addresses
    
    resources :contacts do
      resources :addresses
    end

    resources :notes

   resources :sessions
   root :to => 'sessions#new'
   match 'logout' => 'sessions#destroy', :as => :logout
  
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  attr_accessible :name, :phoneno,  :fax,  :legal_name, :website_url, :status
 
  has_many :addresses, :as => :addressable  
  has_many :notes, :as => :notable
  has_many :contacts

   validates_uniqueness_of :name, :message => 'Already Customer exist'
   validates_presence_of :phoneno, :message => 'Invalid phone number' 
   validates_presence_of :fax, :message => 'Invalid phone number' 
   validates_presence_of :legal_name, :message => 'Should not be blank' 
   validates_presence_of :website_url, :message => 'Should not be blank'


   def self.search(search1, search2) 
    if search1.present?
          where('name LIKE ?', "%#{search1}%")
            elsif search2.present?
              where('phoneno LIKE ?', "%#{search2}%") 
                   else  
                         scoped  
             end  
   end
  def has_primary_address?
    addresses.each do |address|
      if address.address_type =="Primary"
        return false
      end
    end
    return true
  end

  def has_primary_contact
    addresses.each do |address|
      if address.address_type =="Primary"
        return false
      end
    end
    return true
  end

  def activate
     self.status = 1
     self.save
  end

  def deactive
     self.status = 0
     self.save
  end

def self.to_csv(options = {})
     customers = Customer.find(:all,:conditions=>['status = 1'])
    CSV.generate(options) do |csv|
    csv << column_names
    all.each do |customer|
      csv << customer.attributes.values_at(*column_names)
    end
  end

    #CSV.generate do |csv|
     #csv << ["Name","Phone No","Fax","Legal Name","Website","Status"]
      #customers.each do |customer|
       # csv << [customer.name,customer.phoneno,customer.fax,customer.legal_name,customer.website_url,customer.status]
      #end
    #end 
  end

 def self.import(file)
   CSV.foreach(file.path, headers: true) do |row|
     customer = find_by_id(row["name"]) || new
     customer.attributes = row.to_hash.slice(*accessible_attributes)
     customer.save!
   end
 end

 # def self.import(file)
 #   CSV.foreach(file.path, headers: true) do |row|
 #   Customer.create! row.to_hash
 #   end
 # end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
 require 'customer_drawer'
 before_filter :require_login
 before_filter :find_customer ,:except=>[:index,:new,:create,:inactive,:import]
 
  def index
  @customers = Customer.where(:status => 1)
   @customers = @customers.search(params[:search1], params[:search2]).order("name").page(params[:page]).per(5)

   respond_to do |format|
      format.html
      format.csv { render text: @customers.to_csv }
      format.pdf do
          #pdf.text customer.phoneno
          #pdf.text customer.fax
          #pdf.text customer.legal_name
          #pdf.text customer.website_url
          #pdf.text customer.status         
          send_data CustomerDrawer.draw(@customers), :filename => 'customer.pdf', :type => 'application/pdf', :disposition => 'inline'
    end
      
    end  
  end

  def import
    Customer.import(params[:file])
        redirect_to customers_path, notice: "customers imported"
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(params[:customer])
      if @customer.save
        redirect_to customers_path
      else
        render action: "new"
      end
  end

  def update
      if @customer.update_attributes(params[:customer])
       redirect_to customers_path
      else
       render action: "edit" 
      end
  end

  def destroy
    @customer.destroy
    redirect_to customers_path 
  end


  def activate
    @customer.activate
    redirect_to customers_path
  end
  

  def deactive
    @customer.deactive
    redirect_to customers_path
  end


def inactive
   @customers = Customer.where(:status => 0)
   @customers = @customers.order("name").page(params[:page]).per(5)
end

private

  def find_customer
    @customer = Customer.find(params[:id])
    if not @customer
      raise  ActiveRecord::RecordNotFound
    end
  end

end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer, :html => { :class => 'form-horizontal customer_form' } do |f| %>

  <div class="control-group">
    <%= f.label :Name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field', :id => 'name_text' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :Phone_Number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :phoneno, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :Fax_Number, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :fax, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="control-group">
    <%= f.label :legal_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :legal_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :website, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :website_url, :class => 'text_field' %>
    </div>
  </div>
  

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customers_path, :class => 'btn' %>
  </div>
<% end %>


<%= stylesheet_link_tag "jquery-ui" %>
<%= javascript_include_tag  "jquery-1.9.1.js", 'jquery-ui', 'jquery.validate.js', 'jquery.validate.min.js' %>
<script>
  
function  validate_function(){
  
$(".customer_form").validate({
  rules: {
    "customer[name]": {
      required: true,
      minlength: 4
    },
    "customer[phoneno]": {
      required: true,
      
    },
    "customer[password]": {
      required: true,
      minlength:6
    },
    "customer[password_confirmation]": {
      required: true,
      equalTo: "#user_password"
    }
  },
  messages: {
   "customer[name]" : {
      required: "Name should not be blank",
      minlength: jQuery.format("At least {0} characters required!")
    },
   "customer[phoneno]" : {
      required: "must be numbers, should not be blank",
      
    },
   "customer[password]" : {
      required: "password should not be blank",
      minlength: jQuery.format("At least {6} characters required!")
    },
   "customer[password_confirmation]" : {
      required: "password should not be blank",
      equalTo: "password should not match"
    }
  }
});

}

$(document).ready(function() {
  
  validate_function();
  
$( "#datepicker" ).datepicker();

 });
</script>

app/views/customers/edit.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/inactive.html.erb
<div class="page-header">
  <h3>Deactivated Customers</h3>
</div>

<table class="tablesorter" style="width:95%;border:1px solid; align:center;" align="center">
<thead>
  <div class="abc">
    <tr style="height:50px"> 
      <th>Name</th>
      <th>Phone No</th>
      <th>Fax</th>
      <th>Legal Name</th>
      <th>Web Site</th>
      <th>Status</th>
    </tr>
 </div>
  </thead>
  <tbody>
    
   <% @customers.each do |customer| %>
   <% if customer.status == 0  %>
      <tr>
        <td><b><%= customer.name %></b></td>
        <td><b><%= customer.phoneno %></b></td>
        <td><b><%= customer.fax %></b></td>
        <td><b><%= customer.legal_name %></b></td>
        <td><b><%= customer.website_url %></b></td>
        <td><%= link_to "Activate", activate_customer_path(customer), :class => 'btn' %>
        </tr>
      <% end %>
    <% end %>
    
  </tbody>
</table>
<div style="float:right; padding-right:28px;">
<%= paginate @customers %>
 </div>
 <%= stylesheet_link_tag 'tablesorter.css' %>
<%= javascript_include_tag  'jquery.tablesorter.min' %>
<script type="text/javascript">

$(document).ready(function() { 
    $("#customer_table").tablesorter({   });  
  } 
</script>

app/views/customers/index.html.erb
<div class="page-header">
  <h4>Customers</h4>
<h5>Import customers</h5>
<%= form_tag import_customers_path, multipart: true do %>
  <%= file_field_tag :file %>
  <%= submit_tag "Import" %>
<% end %>
<div style="float:right; padding-right:35px;" >
  <%= link_to "Export CSV", customers_path(format: "csv"), :class => 'btn' %> 
</div>
<div style="float:right; padding-right:35px;" >
<%= link_to 'PDF Format', customers_path(format: "pdf"), :class =>'btn' %>
  </div>
    <%= form_tag customers_path, :method => 'get' do %>  
      <p> 
        <div style="float:left; padding-left:35px;" >

       Name: <%= text_field_tag :search1, params[:search1] %>  
       Phone number: <%= text_field_tag :search2, params[:search2] %>
        <%= submit_tag "Search", :name => nil %> 
        </div>
      </p>  
    <% end %>  
    <table class="tablesorter" id="customer_table" style="width:95%;border:1px solid; align:center;" align="center">
   
<!--
<table class="table table-striped" style="width:95%;border:1px solid; align:center;" align="center"> -->
<thead>

    <tr style="height:50px">
      <th>Name</th>
      <th>Phone No</th>
      <th>Fax</th>
      <th>Legal Name</th>
      <th>Web Site</th>
      <th>Status</th>
    </tr>
 
  </thead>
  <tbody>
    
   <% @customers.each do |customer| %>
   <% if customer.status == 1  %>
      <tr>
        <td><b><%= link_to customer.name, customer_path(customer.id) %></b></td>
        <td><b><%= customer.phoneno %></b></td>
        <td><b><%= customer.fax %></b></td>
        <td><b><%= customer.legal_name %></b></td>
        <td><b><%= customer.website_url %></b></td>
        <td><%= link_to "Deactivate", deactive_customer_path(customer), :class => 'btn' %>
        </tr>
      <% end %>
    <% end %>
    
  </tbody>
</table>
<div style="float:right; padding-right:28px;">
<%= paginate @customers %>
 </div>
 </div>
 <%= stylesheet_link_tag 'tablesorter.css' %>
<%= javascript_include_tag  'jquery.tablesorter.min' %>
<script type="text/javascript">

$(document).ready(function() { 
    $("#customer_table").tablesorter({   });  
  } 
</script>

app/views/customers/new.html.erb
<%- model_class = Customer -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/customers/show.html.erb
<div class="page-header">
  <h1>Customer</h1>
</div>
<table width="100%" border="1">
          <tbody>
            <tr valign="top">
              <td align="left" width="35%">
                <table  style="width:100%;">
                  <tr>
                  <th>Name</th>
                  <td> <%= @customer.name %></td></tr>
                  <tr><th>Phone</th><td><%= @customer.phoneno %></td></tr>
                  <tr>
                  <th>Fax</th>
                  <td> <%= @customer.fax %></td>
                  </tr>
                  <th>Legal Name</th>
                  <td> <%= @customer.legal_name %></td></tr>
                 <tr><th>Website</th><td><%= @customer.website_url %></td></tr>
                 <tr><td align="center">
                <%= link_to "Edit",edit_customer_path(@customer), :class => 'btn' %>
                <%= link_to "Delete",customer_path(@customer),:method => 'delete',:confirm =>'Are you sure?',:class => 'btn' %>
              </td></tr>
                </table>
              </td>

              <td width="33%" valign="top">
              <%= link_to "Add Address", new_customer_address_path(@customer) %>
            <table width = "100%">
            <% @customer.addresses.in_groups_of(3) do |address_list| %>
              <tr valign="top">
                <% address_list.each do |address| %>
                <td width="30%">
                  <% if address %>
                  <table>
                    <tr>
                    <td> <%= address.address_type %></td></tr>
                    <tr>
                    <td><%= address.street1 %>, <%= address.street2 %></td></tr>
                    <tr>
                    <td> <%= address.city %>, <%= address.state %></td></tr>
                    <tr><td><%= address.country %>, <%= address.zip %></td></tr>
                     <tr><td>
                      <%= link_to "Edit",edit_customer_address_path(@customer,address) %>&nbsp;
                      <%= link_to "Delete", customer_address_path(@customer,address),:method => 'delete', :confirm =>  'Are you sure?' %>
                    </td></tr>
                  </table>
                  <% end %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </table>
      </td>

        <td width="33%" valign="top">
              <%= link_to "Add Contacts", new_customer_contact_path(@customer) %>
            <table width = "100%">
            <% @customer.contacts.in_groups_of(3) do |contact_list| %>
              <tr valign="top">
                <% contact_list.each do |contact| %>
                <td width="30%">
                  <% if contact %>
                  <table>
                    <tr>
                    <td><%= link_to contact.name, customer_contact_path(@customer,contact)%></td></tr>
                    <tr>
                    <td> <%= contact.email %></td></tr>
                    </table>
                  <% end %>
            </td>
            <% end %>
          </tr>
          <% end %>
        </table>
      </td>

    <table width = "100%"><tr valign="top"><h3>Notes</h3>
      <%= link_to "Add Notes", new_customer_note_path(@customer) %>
            <td>
              <% @customer.notes.each do |note| %>
              <table>
                <tr>
                <td> <%= note.category %> </td></tr>
                <tr>
                <td><%= note.description %></td></tr>
                </table>
                 <%= link_to "Edit",edit_customer_note_path(@customer,note) %>&nbsp;
                <%= link_to "Delete", customer_note_path(@customer,note),:method => 'delete', :confirm =>  'Are you sure?' %>
                <% end %>
                <tr><td>
               
                </td></tr>

            </td></tr>
    </table>