config/routes.rb
ModelCustmoers::Application.routes.draw do
  resources :customers do
    collection do
       post :import 
       get :inactive
       post :inactive       
     end
     member do
       get :deactive
       get :activate
      end
    resources :addresses
    resources :notes
    resources :contacts
  end
  resources :users do
    collection do
      get :forgot_password  
      post :forgot_password
      get :edit_password
      put  :edit_password
      get :inactive
      post :inactive
    end 
     member do
       get :deactive
       get :activate
      end
  end
    resources :addresses
    
    resources :contacts do
      resources :addresses
    end

    resources :notes

   resources :sessions
   root :to => 'sessions#new'
   match 'logout' => 'sessions#destroy', :as => :logout
  
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :email, :facebook_url, :linkedn_url, :mobile, :name, :phone_no, :twitter_url, :address_type, :street1, :street2, :city, :state, :country, :zip, :addressable_id, :addressable_type
  has_many :addresses, :as => :addressable  

  belongs_to :customer
  
  validates_presence_of :name,:message => 'Should not be blank'
  validates_presence_of :email, :message => 'Should not be blank'
  validates_format_of :email,
                      :with => /^([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})$/i , 
                      :message => 'invalid email'
  validates_numericality_of :phone_no, :message => 'Invalid phone number' 
  validates_numericality_of :mobile, :message => 'Invalid mobile number'
  validates_presence_of :street1, :message => 'Should not be blank' 
  validates_presence_of :street2, :message => 'Should not be blank'
  validates_presence_of :city, :message => 'Should not be blank' 
  validates_presence_of :state, :message => 'Should not be blank' 
  validates_presence_of :country, :message => 'Should not be blank'
  validates_numericality_of :zip, :message => 'Invalid zip code' 
 
 end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  layout "application"
   before_filter :require_login
   before_filter :find_customer

   before_filter :find_contact,:except => [:new, :create]


  def show
  end

 
  def new
    @contact = Contact.new
  end

 
  def edit
  end

  def create
    @contact = @customer.contacts.build(params[:contact])
      if @contact.save!
        redirect_to customer_path(@customer)
      else
        render "new" 
      end
  end

  
  def update
    if @customer.contacts.update_attributes(params[:address])
        redirect_to customer_path(@customer)
    else
      render "edit" 
    end
    
  end

  
  def destroy
    @contact.destroy
    redirect_to customer_path(@customer)
  end

  private

  def find_customer
    @customer = Customer.find(params[:customer_id])
    if not @customer
      raise ActiveRecord::RecordNotFound
    end
  end

  def find_contact
    @contact = @customer.contacts.find(params[:id])
    if not @contact
      raise ActiveRecord::RecordNotFound
    end
  end


end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<%= form_for contact, :url=> customer_contacts_path(customer),:html => { :class => 'form-horizontal' } do |f| %>

 <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :phone_no, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :phone_no, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :mobile, :class => 'control-label' %>
    <div class="controls">
      <%= f.number_field :mobile, :class => 'number_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :linkedn_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :linkedn_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :facebook_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :facebook_url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :twitter_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :twitter_url, :class => 'text_field' %>
    </div>
  </div>

   <div class="control-group">
    <%= f.label :Address_Type, :class => 'control-label' %>
    <div class="controls">
     <%= f.select :address_type, options_for_select(["Primary","Billing", "Shipping"]) %>
    </div>
  </div>
   <div class="control-group">
    <%= f.label :street1, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :street1, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :street2, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :street2, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :city, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :city, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :state, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :state, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :country, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :country, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :zip, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :zip, :class => 'text_field' %>
    </div>
  </div>
  
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                customer_path(@customer), :class => 'btn' %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contacts/index.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone_no) %></th>
      <th><%= model_class.human_attribute_name(:mobile) %></th>
      <th><%= model_class.human_attribute_name(:linkedn_url) %></th>
      <th><%= model_class.human_attribute_name(:facebook_url) %></th>
      <th><%= model_class.human_attribute_name(:twitter_url) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to contact.id, contact_path(contact) %></td>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone_no %></td>
        <td><%= contact.mobile %></td>
        <td><%= contact.linkedn_url %></td>
        <td><%= contact.facebook_url %></td>
        <td><%= contact.twitter_url %></td>
        <td><%=l contact.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_contact_path(contact), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      customer_contact_path(contact),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_contact_path,
            :class => 'btn btn-primary' %>

app/views/contacts/new.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form',:locals=>{ :contact => @contact, :customer=>@customer } %>

app/views/contacts/show.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>
<%= link_to "Add Address", new_contact_address_path(@contact) %>
<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @contact.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @contact.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:phone_no) %>:</strong></dt>
  <dd><%= @contact.phone_no %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mobile) %>:</strong></dt>
  <dd><%= @contact.mobile %></dd>
  <dt><strong><%= model_class.human_attribute_name(:linkedn_url) %>:</strong></dt>
  <dd><%= @contact.linkedn_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:facebook_url) %>:</strong></dt>
  <dd><%= @contact.facebook_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:twitter_url) %>:</strong></dt>
  <dd><%= @contact.twitter_url %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              customer_path(@contact.customer_id), :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_customer_contact_path(@customer,@contact), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              customer_contact_path(@customer,@contact),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>