config/routes.rb
ModelCustmoers::Application.routes.draw do
  resources :customers do
    collection do
       post :import 
       get :inactive
       post :inactive       
     end
     member do
       get :deactive
       get :activate
      end
    resources :addresses
    resources :notes
    resources :contacts
  end
  resources :users do
    collection do
      get :forgot_password  
      post :forgot_password
      get :edit_password
      put  :edit_password
      get :inactive
      post :inactive
    end 
     member do
       get :deactive
       get :activate
      end
  end
    resources :addresses
    
    resources :contacts do
      resources :addresses
    end

    resources :notes

   resources :sessions
   root :to => 'sessions#new'
   match 'logout' => 'sessions#destroy', :as => :logout
  
end

app/views/layouts/_flash_messages.html.erb
<div>
  <% flash.each do |key, value| %>
    <div class="<%= flash_class(key) %> fade in">
      <a href="#" data-dismiss="alert" class="close">×</a>
      <%= value %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <body style="background-color:#f0f0f0;">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "rails.validations" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/flash_messages' %>
  <% flash.each do |name, message| %>
   <div style="font-size:10px;font-family:verdana;color:red;" >
   <%= content_tag :div, message, :id => "flash_#{name}" ,:align => "center"%>
   </div>
  <% end %>
  </body>  

<div>
  <% if @current_user %>
   <h1 style="float:left;" align="top">Model Customers</h1>
      <div style = "float:right;font-size:14px;">
       <%= image_tag @current_user.photo(:mini) %>
  Hi <%= current_user.username %> |
         <%= link_to "Profile " , user_path(current_user) %>|<%= link_to "change password " ,edit_password_users_path  %>|<%= link_to " logout",logout_path %>
      </div> <br>
      <br>
      <br>
      <br> 
<div class="container">  
<div class="row">  
<ul class="nav nav-pills ">  
<li class="<%= 'active' if current_page?(new_customer_path) %>"><%= link_to "New Customer", new_customer_path, :class => 'btn' %></li>&nbsp;
<li class="<%= 'active' if current_page?(customers_path) %>"><%= link_to "Customers List", customers_path, :class => 'btn' %></li>&nbsp;
   <li class="<%= 'active' if current_page?(inactive_customers_path) %>"><%= link_to "Deactivated Customers",inactive_customers_path,  :class => 'btn' %></li>&nbsp;
    <% if current_user.role == "Admin" %>
     <li class="<%= 'active' if current_page?(users_path) %>"><%= link_to "Users List", users_path,:class => 'btn' %></li>&nbsp;
      <li class="<%= 'active' if current_page?(inactive_users_path) %>"><%= link_to "Deactivated Users", inactive_users_path,  :class => 'btn' %></li>
    <% end %>
   </ul>  
</div>
</div> 
    
    </div>
    
    <br/>

<% end %>
<%= yield %>

</body>
</head>
</html>